management:
  endpoint:
    health:
      show:
        detals: always 
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      wavefront:
        uri: https://surf.wavefront.com
        api:
          key: "{cipher}QWdCRUppRi9tc1lHNjBBSW1UbFZDRy9Jbmp6VWZNMGpIVnZSbFZVZDNhYXRCWlY5OEtnOUxSZW81NnJjSzVSQzFZKzNleXNWM2xFcTIwOTA4T2xKNGxQT0d3cFVsQXhRNWRtT255YWdFT3dydDdJdytmUmJTRG5HaTRQa2M3Umtvek5qaE5VZm55MGhRdEFNZjlMamxBelJFYlE3NXhobEtXNGpCMEg0aHhIVExicXBialQyTHRKcjU0c3RVR0k0YzhmeFgyNTZLUlgrbmdMeit0Rys4SkVNRlpPMmkrNGJNTTFuNmRJeVhJelVPNVVqWVdXT3AzWmpGQjNmUEF6L1pvc0EybTVod0NBb3JBLysydEhaM1lwa0l6TXZ1cjVjWGN1R2lpSWR5UXo2cWFFYUJiWUJOK29VTlhheGRUZ2tzbm5CZ213eDY3aXNFMEF3d2ZBa21DaUdWaDBpK0RnZ0EwR0s0THRNMGZwU24rdGFrWTNUZ3hST2ZEQWJiUzhGNzZlcWI0SEVlN2hmY3dkSTRlS2huM3hiSzFmV1dVL3dnWWhyTnBzU01EczRGQ25KKytTUERmVXlnNXlRbk9NVytqYjV6ZkY2aVdlbysxbDljMnJ5Q1cxZ2NjQmFVM0xlNE9xRDVTd2xvRWxvUzcvZjl5ejE0ZGsybnVSVkdrSmdlVzJFaGZ1LzJXZlhROU1wSkdEbzcxanUxb2ZpaDVEeU1zb0ViTnRmUnhLK3RzQkNrcGFnc1k1aElxa2J6NHU3QnJ0T21PVU9ud2V1SHNzZ2ZRc0QybWZvalFjd3RKOE5GZ3FiZDM1Y1RRc2RkWHZtcmlBa0RyL1c4ay90VFBTQ2IxdTUzUVVhaFJHaGludGh4VGNRUldKemRhZExVMTRCbC9QMm9vZmhseG5wQmRtcVRpTm9HQXNJK0dPcTJxQlpTSkxNdFIrZDNybUZ0c2FwUGRHU3NERUZDU1hycmJZazlycUFFTEFjWnJpWnRFWGpkZy9kVkhjS1ZETkw2RzJNbWRnPQo="
