management:
  endpoint:
    health:
      show:
        detals: always 
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      wavefront:
        uri: https://surf.wavefront.com
        api:
          key: '{cipher}AgBEJiF/msYG60AImTlVCG/InjzUfM0jHVvRlVUd3aatBZV98Kg9LReo56rcK5RC1Y+3eysV3lEq20908OlJ4lPOGwpUlAxQ5dmOnyagEOwrt7Iw+fRbSDnGi4Pkc7RkozNjhNUfny0hQtAMf9LjlAzREbQ75xhlKW4jB0H4hxHTLbqpbjT2LtJr54stUGI4c8fxX256KRX+ngLz+tG+8JEMFZO2i+4bMM1n6dIyXIzUO5UjYWWOp3ZjFB3fPAz/ZosA2m5hwCAorA/+2tHZ3YpkIzMvur5cXcuGiiIdyQz6qaEaBbYBN+oUNXaxdTgksnnBgmwx67isE0AwwfAkmCiGVh0i+DggA0GK4LtM0fpSn+takY3TgxROfDAbbS8F76eqb4HEe7hfcwdI4eKhn3xbK1fWWU/wgYhrNpsSMDs4FCnJ++SPDfUyg5yQnOMW+jb5zfF6iWeo+1l9c2ryCW1gccBaU3Le4OqD5SwloEloS7/f9yz14dk2nuRVGkJgeW2Ehfu/2WfXQ9MpJGDo71ju1ofih5DyMsoEbNtfRxK+tsBCkpagsY5hIqkbz4u7BrtOmOUOnweuHssgfQsD2mfojQcwtJ8NFgqbd35cTQsddXvmriAkDr/W8k/tTPSCb1u53QUahRGhinthxTcQRWJzdadLU14Bl/P2oofhlxnpBdmqTiNoGAsI+GOq2qBZSJLMtR+d3rmFtsapPdGSsDEFCSXrrbYk9rqAELAcZriZtEXjdg/dVHcKVDNL6G2Mmdg='